FROM tomcat
COPY lib/json-20200518.jar /usr/local/tomcat/lib
COPY lib/mysql-connector-java-8.0.22.jar /usr/local/tomcat/lib
COPY lib/jjwt-0.9.1.jar /usr/local/tomcat/lib
COPY lib/jackson-core-2.9.6.jar /usr/local/tomcat/lib
COPY lib/jackson-annotations-2.9.0.jar /usr/local/tomcat/lib
COPY lib/jackson-databind-2.9.6.jar /usr/local/tomcat/lib
COPY lib/bcprov-jdk15on-1.67.jar /usr/local/tomcat/lib


WORKDIR /usr/local/tomcat/webapps
ENV CLASSPATH="/usr/local/tomcat/lib/servlet-api.jar:/usr/local/tomcat/lib/json-20200518.jar:/usr/local/tomcat/lib/tomcat-jdbc.jar:/usr/local/tomcat/lib/jjwt-0.9.1.jar:/usr/local/tomcat/lib/jackson-databind-2.9.6.jar:/usr/local/tomcat/lib/jackson-core-2.9.6.jar:/usr/local/tomcat/lib/jackson-annotations-2.9.0.jar:/usr/local/tomcat/lib/bcprov-jdk15on-1.67.jar"
